# Generated by Django 5.2.8 on 2025-11-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('SC', 'Scheduled'), ('PU', 'Published')], default='DR', max_length=2),
        ),
    ]
