from django.test import TestCase

from ...models import Topic
from ...forms import TopicForm


class TopicFormTest(TestCase):
    """Test suite for TopicForm"""

    def test_form_has_correct_fields(self):
        """Test that form includes all expected fields"""
        form = TopicForm()
        expected_fields = ['name', 'description']
        self.assertEqual(list(form.fields.keys()), expected_fields)

    def test_form_valid_with_name_only(self):
        """Test form is valid with only name (description is optional)"""
        form_data = {
            'name': 'Technology',
            'description': '',
        }
        form = TopicForm(data=form_data)
        self.assertTrue(form.is_valid(), form.errors)

    def test_form_valid_with_name_and_description(self):
        """Test form is valid with both name and description"""
        form_data = {
            'name': 'Technology',
            'description': 'All about tech',
        }
        form = TopicForm(data=form_data)
        self.assertTrue(form.is_valid(), form.errors)

    def test_form_invalid_without_name(self):
        """Test form is invalid without name"""
        form_data = {
            'description': 'Description only',
        }
        form = TopicForm(data=form_data)
        self.assertFalse(form.is_valid())
        self.assertIn('name', form.errors)

    def test_form_valid_with_empty_description(self):
        """Test form accepts empty description"""
        form_data = {
            'name': 'Technology',
            'description': '',
        }
        form = TopicForm(data=form_data)
        self.assertTrue(form.is_valid(), form.errors)

    def test_form_save_creates_topic(self):
        """Test that saving form creates topic in database"""
        form_data = {
            'name': 'New Topic',
            'description': 'Topic description',
        }
        form = TopicForm(data=form_data)
        self.assertTrue(form.is_valid())
        
        topic = form.save()
        
        self.assertIsNotNone(topic.id)
        self.assertEqual(topic.name, 'New Topic')
        self.assertEqual(topic.description, 'Topic description')
        # Slug should be auto-generated by model
        self.assertEqual(topic.slug, 'new-topic')

    def test_form_edit_existing_topic(self):
        """Test form can edit existing topic"""
        topic = Topic.objects.create(
            name='Original Name',
            description='Original description'
        )
        
        form_data = {
            'name': 'Updated Name',
            'description': 'Updated description',
        }
        form = TopicForm(data=form_data, instance=topic)
        self.assertTrue(form.is_valid())
        
        updated_topic = form.save()
        
        self.assertEqual(updated_topic.id, topic.id)
        self.assertEqual(updated_topic.name, 'Updated Name')
        self.assertEqual(updated_topic.description, 'Updated description')

    def test_form_preserves_slug_on_name_change(self):
        """Test that slug is not regenerated when name changes via form"""
        topic = Topic.objects.create(name='Original Name')
        original_slug = topic.slug
        
        form_data = {
            'name': 'Completely Different Name',
            'description': '',
        }
        form = TopicForm(data=form_data, instance=topic)
        self.assertTrue(form.is_valid())
        
        updated_topic = form.save()
        
        # Slug should remain unchanged (as per model save() logic)
        self.assertEqual(updated_topic.slug, original_slug)

    def test_form_accepts_long_description(self):
        """Test form accepts lengthy descriptions"""
        long_description = 'A' * 1000  # 1000 characters
        form_data = {
            'name': 'Topic',
            'description': long_description,
        }
        form = TopicForm(data=form_data)
        self.assertTrue(form.is_valid(), form.errors)

    def test_form_name_max_length(self):
        """Test form enforces name max length (100 chars as per model)"""
        # This test verifies the form respects the model's max_length constraint
        long_name = 'A' * 101  # 101 characters, exceeds max_length
        form_data = {
            'name': long_name,
            'description': 'Description',
        }
        form = TopicForm(data=form_data)
        self.assertFalse(form.is_valid())
        self.assertIn('name', form.errors)


